# Decisões com Python
## Logica booleana, operadores e condicionais

Quando o programa começa a tomar caminhos diferentes de acordo com condições.

1. Booleanos

Booleano representa apenas dois estados: True ou False

In [ ]:
maior_de_idade = True
possui_cupom = False

In [ ]:
nota = 7.5
frequencia = 88

print(nota >= 7)
print(frequencia >= 75)

True
True

# Operadores Lógicos

and = exige que as duas condições ou mais sejam verdadeiras.
or = exige que pelo menos UMA condição seja verdadeira.
not = inverte o resultado.

# Operadores Relacionais

== é igual a?

!= é diferente de

> É maior que

>= É maior ou igual a

< É menor que

<= é menor ou igual a

In [ ]:
nota = 6.5
frequencia = 85
aprovado = nota >= 7 and frequencia >= 75
print(aprovado)

False

# If / Else

If = testa a condição e apresenta a condição

Else: representa o caminho alternativo; O else, atende caso nenhuma condição anterior esteja verdadeira.

In [ ]:
nota = 6
if nota >= 7:
  print('Aprovado')
else:
  print('Reprovado')

Reprovado

# Elif

Usa quando existem mais de duas possibilidades; O elif significa "senão, se", ou seja: Ele oferece outra condição quuandos as anteriores não foram atendidas.

In [ ]:
nota = 8.9
if nota >= 7:
  print('Aprovado')
elif nota >= 5:
  print('Recuperação')
else:
  print('Reprovado')

Aprovado

# Base de alunos

Vamos classificar os alunos por meio da nossa base de dados alunos_desempenho.csv

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving alunos_desempenho.csv to alunos_desempenho.csv

In [ ]:
import pandas as pd
arquivo = next(iter(uploaded))
df = pd.read_csv(arquivo)
df.head()

      aluno  nota_1  nota_2  frequencia
0  Aluno 01    10.0     6.3          51
1  Aluno 02     9.5     9.1          92
2  Aluno 03     8.7     7.3          64
3  Aluno 04     8.4     6.3          81
4  Aluno 05     7.2     4.5          78

# Criando uma função para classificar cada aluno em: média e frequencia

In [ ]:
def classificar(media, frequencia):
  if media >= 7 and frequencia >= 75:
    return 'Aprovado'
  elif media >= 5 and frequencia >= 75:
    return 'Recuperação'
  else:
    return 'Reprovado'

df['media'] = (df['nota_1'] + df['nota_2']) / 2
df['situação'] = df.apply(lambda linha: classificar(linha['media'], linha['frequencia']), axis=1)
df.head()

      aluno  nota_1  nota_2  frequencia  media     situação
0  Aluno 01    10.0     6.3          51   8.15    Reprovado
1  Aluno 02     9.5     9.1          92   9.30     Aprovado
2  Aluno 03     8.7     7.3          64   8.00    Reprovado
3  Aluno 04     8.4     6.3          81   7.35     Aprovado
4  Aluno 05     7.2     4.5          78   5.85  Recuperação

# Desafio loja

1. Fazer o upload de pedidos_loja.csv e criar uma regra de desconto:



*   Cliente VIP recebe 15%
*   compra acima de R$ 150 recebe 10%
*   quem usou cupom recebe 5%
*   demais casos não recebem desconto.

In [ ]:
uploaded = files.upload()
arquivo = next(iter(uploaded))
import pandas as pd
pedidos = pd.read_csv(arquivo)

Saving pedidos_loja.csv to pedidos_loja.csv

In [ ]:
df = pd.read_csv(arquivo)
df.head()

   pedido_id  valor_compra tipo_cliente  usou_cupom
0          1        253.71         novo       False
1          2        172.95   recorrente       False
2          3        207.40         novo       False
3          4        121.31          vip        True
4          5        113.62   recorrente       False

In [ ]:
# Desafio

def desconto(valor, tipo_cliente, usou_cupom):
  if tipo_cliente == 'vip':
    return 0.15
  elif valor > 150:
    return 0.10
  elif usou_cupom == True:
    return 0.05
  else:
    return 0.00

pedidos['percentual_desconto'] = pedidos.apply(lambda linha: desconto(
    linha['valor_compra'],
    linha['tipo_cliente'],
    linha['usou_cupom']
),
axis=1
)

#Calcular o valor final para as duas casas decimais
pedidos['valor_final'] = (pedidos['valor_compra'] * (1 - pedidos['percentual_desconto'])).round(2)
pedidos.head()

,pedido_id,valor_compra,tipo_cliente,usou_cupom,percentual_desconto,valor_final
0,1,253.71,novo,False,0.10,228.34
1,2,172.95,recorrente,False,0.10,155.66
2,3,207.40,novo,False,0.10,186.66
3,4,121.31,vip,True,0.15,103.11
4,5,113.62,recorrente,False,0.00,113.62

In [ ]:
# Sem lambda recebe uma linha e devolve o percentual de desconto
def calcular_desconto(linha):
  if linha['tipo_cliente'] == 'vip':
    return 0.15

  elif linha['valor_compra'] > 150:
    return 0.10

  elif linha['usou_cupom']:
    return 0.05

  else:
    return 0.00

# Aplica a função de cada linha da tabela
pedidos['percentual_desconto'] = pedidos.apply(calcular_desconto, axis=1).round(2)
pedidos.head()

,pedido_id,valor_compra,tipo_cliente,usou_cupom,percentual_desconto,valor_final
0,1,253.71,novo,False,0.10,228.34
1,2,172.95,recorrente,False,0.10,155.66
2,3,207.40,novo,False,0.10,186.66
3,4,121.31,vip,True,0.15,103.11
4,5,113.62,recorrente,False,0.00,113.62